// Colors
#define COLOR_GREY			0xAFAFAFAA
#define COLOR_GREEN 		0x4DAD2B2B 
#define COLOR_YELLOW 		0xFFFF00AA
#define COLOR_LIGHTBLUE 	0x33CCFFAA
#define COLOR_LIGHTRED 		0xFF6347AA
#define COLOR_DRED			0xb40404FF
#define COLOR_BLUE 			0x3350FFFF
#define COLOR_LIGHT 		0xB8DBFFFF
#define COLOR_WHITE 		0xFFFFFFFF
#define COLOR_PURPLE 		0xC2A2DAAA
#define COLOR_RED 			0xFF0000FF
#define COLOR_TEAL 			0x67AAB1FF
#define COLOR_NON 			0xE7AAA5A5
#define	COLOR_ORANGE    	0xFF9D00FF
#define	COLOR_LORANGE    	0xFFA14FFF // light orange

#define COLOR_ACHAT 0xEDD33EFF
#define COLOR_RCHAT 0xBE80EDFF
#define COLOR_DCHAT 0xFF2945FF
#define COLOR_FCHAT 0x00C8FFFF


// culori texte
#define BLUE 		"{3366CC}"
#define WHITE 		"{FFFFFF}"
#define TEAL 		"{67AAB1}"
#define GREEN 		"{4DAD2B}"
#define GREY 		"{BABABA}"
#define YELLOW 		"{FFFF00}"
#define DRED 		"{A40808}"
#define RED 		"{FF0000}"
#define ANNO 		"{2587CE}"
#define NON			"{E7AAA5}"
#define SYN			"{B8DBFF}"
#define	CREM    	"{D2B48C}"
#define	ORANGE    	"{FF9D00}"
#define	LORANGE    	"{FFA14F}"
#define LABEL 		"{FF5000}"

// Dialogs
#define DIALOG_LOGIN 		(1)
#define DIALOG_REGISTER 	(3)
#define DIALOG_SEX			(4)
#define DIALOG_AGE			(5)
#define DIALOG_EMAIL		(6)
#define DIALOG_GENERAL		(7)
#define DIALOG_BLOCK		(8)
#define DIALOG_NULL			(9)
#define DIALOG_GUNLIC		(10)//+3
#define DIALOG_INTERIORS	(14)//+3
#define DIALOG_SELLHOUSETOSTATE (18)
#define DIALOG_CHECKPOINT	(19)
#define DIALOG_HOUSEMENU	(20)



// Others
#define MAX_GROUPS 		20

#define SPAWN_SKIN 		184
#define SCM 			SendClientMessage


// news
new vehName[][] = { "Landstalker", "Bravura", "Buffalo", "Linerunner", "Perrenial", "Sentinel", "Dumper", "Firetruck", "Trashmaster", "Stretch", "Manana", "Infernus", "Voodoo", "Pony", "Mule", "Cheetah", "Ambulance", "Leviathan", "Moonbeam", "Esperanto", "Taxi", "Washington", "Bobcat", "Whoopee", "BF Injection", "Hunter", "Premier",
"Enforcer", "Securicar", "Banshee", "Predator", "Bus", "Rhino", "Barracks", "Hotknife", "Trailer", "Previon", "Coach", "Cabbie", "Stallion", "Rumpo", "RC Bandit", "Romero", "Packer", "Monster", "Admiral", "Squalo", "Seasparrow", "Pizzaboy", "Tram", "Trailer", "Turismo", "Speeder", "Reefer", "Tropic", "Flatbed", "Yankee", "Caddy",
"Solair", "Berkley's RC Van", "Skimmer", "PCJ-600", "Faggio", "Freeway", "RC Baron", "RC Raider", "Glendale", "Oceanic", "Sanchez", "Sparrow", "Patriot", "Quad", "Coastguard", "Dinghy", "Hermes", "Sabre", "Rustler", "ZR-350", "Walton", "Regina", "Comet", "BMX", "Burrito", "Camper", "Marquis", "Baggage", "Dozer", "Maverick",
"News Chopper", "Rancher", "FBI Rancher", "Virgo", "Greenwood", "Jetmax", "Hotring", "Sandking", "Blista Compact", "Police Maverick", "Boxvillde", "Benson", "Mesa", "RC Goblin", "Hotring Racer A", "Hotring Racer B", "Bloodring Banger", "Rancher", "Super GT", "Elegant", "Journey", "Bike", "Mountain Bike", "Beagle", "Cropduster",
"Stunt", "Tanker", "Roadtrain", "Nebula", "Majestic", "Buccaneer", "Shamal", "Hydra", "FCR-900", "NRG-500", "HPV1000", "Cement Truck", "Tow Truck", "Fortune", "Cadrona", "FBI Truck", "Willard", "Forklift", "Tractor", "Combine", "Feltzer", "Remington", "Slamvan", "Blade", "Freight", "Streak", "Vortex", "Vincent", "Bullet", "Clover",
"Sadler", "Firetruck", "Hustler", "Intruder", "Primo", "Cargobob", "Tampa", "Sunrise", "Merit", "Utility", "Nevada", "Yosemite", "Windsor", "Monster", "Monster", "Uranus", "Jester", "Sultan", "Stratum", "Elegy", "Raindance", "RC Tiger", "Flash", "Tahoma", "Savanna", "Bandito", "Freight Flat", "Streak Carriage", "Kart", "Mower", "Dune",
"Sweeper", "Broadway", "Tornado", "AT-400", "DFT-30", "Huntley", "Stafford", "BF-400", "News Van", "Tug", "Trailer", "Emperor", "Wayfarer", "Euros", "Hotdog", "Club", "Freight Box", "Trailer", "Andromada", "Dodo", "RC Cam", "Launch", "Police Car", "Police Car", "Police Car", "Police Ranger", "Picador", "S.W.A.T", "Alpha", "Phoenix",
"Glendale", "Sadler", "Luggage", "Luggage", "Stairs", "Boxville", "Tiller", "Utility Trailer" };
